[build]
  command = "npm run build"
  # This overrides the UI publish directory setting
  # The plugin will still manage the actual publish output
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

